const points = {
    PREMIUM_MULTIPLIER: 3,
    JOURNAL_SUBMISSION_POINTS: 100,
    GAME_FINISH_POINTS: 200,
    QUESTION_CORRECT: 40,
    QUESTION_INCORRECT: 5,
    STREAK_BONUS: 20,
    FULL_STREAK: 100,
    NEW_FRIEND: 15,
    DAILY_MESSAGE: 5
};

export default points;